### ISSUE TITLE
Why Python 2.7?

### ISSUE THREAD

**Issue by electron0zero** [MQFN/MQFN#1]
Why our Dockerfile uses python 2.7 as a base image, why not python3?

**Comment by RiflerRick** [comment]
The entire software is written in python 2.7. I would like to keep it that way

**Comment by electron0zero** [comment]
@RiflerRick if you need help moving it to Python3, I can port this code to Python3?

**Comment by RiflerRick** [comment]
@electron0zero Actually many packages and dependencies in the code are in python 2.7....I would not recommend changing to python3
